# The URL the site will be built for
base_url = "https://anub.is"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "class"


# A list of files for additional JSON TextMate grammars
extra_grammars = ["uiua-syntax-highlighting/uiua.grammar.json"]

# A list of files for additional JSON TextMate themes
extra_themes = ["uiua-syntax-highlighting/uiua.theme.json"]

theme = "uiua"

[extra]
# Put all your custom variables here
